### ISSUE TITLE
Should edge's be labelled from class name rather than field name?

### ISSUE THREAD

**Issue by Andersmholmgren** [Pajn/Neo4jDart#10]
I noticed that the labels for the edges in my graph were being generated from the field name rather than the type.

e.g. for a model like

```
class Actor extends Person {
  List<Role> myRoles;
}
```

the label would by `myRoles` rather than `Role`.

This is not what I expected and seems odd to me. Is there a reason it was done that way?

**Comment by Pajn** [comment]
The reason for this is that you may have multiple edges between two nodes based on the same class.
For example if you had
```
class Actor extends Person {
  List<Role> actedIn;
  List<Role> voiceIn;
}
```

As the property name are guaranteed to be unique it's an easy solution for such scenarios. It's also creates constant behaviour for edges with and without a class. The chosen solution simply fit our use case with the least amount of hassle.

Do you have a use case where you need a different behaviour?

**Comment by Andersmholmgren** [comment]
Ah I see. Makes sense.

I thought I saw somewhere that you could have inheritance on relationships as well (like association classes in UML). So to cook up a contrived example

```
abstract class MovieParticipant {
   DateTime startDate;
}

class ActedIn extends MovieParticipant {
}

class Directed extends MovieParticipant {
} 

class Person {
  List<MovieParticipant> roles;
}
```

```
CREATE (clint:Person {name: 'Clint Eastwood'}) -[:ACTED_IN {role: 'Harry'}]-> (dh:Movie {name: 'Dirty Harry'})

CREATE (clint:Person {name: 'Clint Eastwood'}) -[:DIRECTED]-> (dh:Movie {name: 'American Sniper'})

MATCH (clint:Person {name: 'Clint Eastwood'}) -[r:MOVIE_PARTICIPANT]-> (movie :Movie) 
RETURN r
```

Clearly you could just have left off the `:MOVIE_PARTICIPANT` part in this case

```
MATCH (clint:Person {name: 'Clint Eastwood'}) -[r]-> (movie :Movie) 
RETURN r
```

but there may be cases where you wanted to do this sort of filtering.

Anyway I couldn't find where I saw this today so maybe I misunderstood something. I am a graph db noob so probably likely I'm confused
