### ISSUE TITLE
The sample dart program doesn't work in WebStorm 12 EAP

### ISSUE THREAD

**Issue by biospring** [Pajn/Neo4jDart#11]
The db.cypher() call within the sample code's main() fails in WebStorm 12 EAP with the following message: '1 positional arguments expected, but 2 found'

If I remove either the query string or the map containing the second parameter of the db.cypher() function, the syntax passes as legal. Any idea on how to resolve this? Thanks.

Code snippet:

import 'package:neo4j_dart/neo4j_dart.dart'; 

main() async {
  var db = new Neo4j();
  var result = await db.cypher('''
        Create (dart:Language {dart})-[:connects_to]->(neo4j:Database {neo4j})
        Return id(dart), id(neo4j)
      ''', {
    'dart': { 'name': 'Dart' },
    'neo4j': { 'name': 'Neo4j' },
  });

  print('successfully created two nodes with id ${result['data'][0]['row'].join(' and ')}');
}

**Comment by Pajn** [comment]
Unfortunately did I forget to update to readme in a previous API change. It's corrected now, thanks for discovering that!

The second parameter to db.cypher is now a named parameter for clarity so you have to do 
```dart
var result = await db.cypher('''
    Create (dart:Language {dart})-[:connects_to]->(neo4j:Database {neo4j})
    Return id(dart), id(neo4j)
  ''', parameters: {
    'dart': { 'name': 'Dart' },
    'neo4j': { 'name': 'Neo4j' },
});
```
instead (notice the _parameters:_ prefix before the Map)

**Comment by biospring** [comment]
Thanks a lot!!!
