### ISSUE TITLE
Neo4j Client Side

### ISSUE THREAD

**Issue by korsvanloon** [Pajn/Neo4jDart#8]
Have you thought about having a client side version?
One that uses `http/browser_client.dart` instead of `http/http.dart`?

**Comment by Pajn** [comment]
The cypher version (lib `neo4j_dart.dart`) would be pretty easy to make a browser version, but Warehouse uses mirrors so that's a bit more heavy lifting to make that work on the client for other than experimenting.
Would you need Warehouse or is `neo4j_dart.dart` enough?

**Comment by korsvanloon** [comment]
Well, just `neo4j_dart` on the client would be great already.

Of course, having decent Warehouse support would be extremely sexy!
But maybe that should be another issue for another time.

**Comment by Pajn** [comment]
Will get to a browser version of `neo4j_dart` later this or next week. If you want it faster, just send a PR. Should be pretty simple.

Warehouse will have to wait if not you or someone else wants to pick it up. I would gladly accept PRs.

**Comment by Pajn** [comment]
Released as 0.3.2
